# Generated by Django 2.1.7 on 2019-03-20 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_comand_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comand',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Game'),
        ),
    ]
